baseURL = 'https://qaflow.dev'
languageCode = 'en-us'
title = 'Blog about QA'
theme = 'anatole'
enableEmoji = true

[params.utterances]
repo="elriyanova/qaflow-comments"
issueTerm="pathname"
label="comment"
theme="preferred-color-scheme"

[params]
title = "Quality means doing it right when no one is looking"
author = "Elvira Riianova"
description = "QA blog has tips, guides and the latest information on everything about QA. Covering topics on how QA Testing can improve Growth and Quality."
profilePicture = "images/profile.jpeg"
gtagId = "G-Y47WQS7RWK"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About me"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/elvira-riianova/"

  [[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/elriyanova"

  [[params.socialIcons]]
icon = "fab fa-medium"
title = "Medium"
url = "https://medium.com/@qaflow.dev"

  [[params.socialIcons]]
icon = "fas fa-envelope"
title = "elriyanova@gmail.com"
url = "mailto:elriyanova@gmail.com"

