baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'qaflow.dev'
theme = 'anatole'

[params]
title = "Hello, my name is Ellie!"
author = "Elvira Riianova"
description = "qaflow.dev"
profilePicture = "images/profile.jpeg"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

